volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    image: ${DOCKERHUB_USERNAME}/kittygram_backend
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - static:/app/staticfiles
      - media:/app/media
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn kittygram_backend.wsgi:application --bind 0.0.0.0:8000"

  frontend:
    image: ${DOCKERHUB_USERNAME}/kittygram_frontend
    volumes:
      - static:/static
    command: cp -r /app/build/. /static/

  gateway:
    image: ${DOCKERHUB_USERNAME}/kittygram_gateway
    depends_on:
      backend:
        condition: service_started
    ports:
      - 9000:80
    volumes:
      - static:/static
      - media:/media
